# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  schedule:
    - cron: "0 7 * * *" # Daily at 7AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Eleventy
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        path: ./awdty

    - name: Checkout mozilla-firefox/firefox
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        repository: mozilla-firefox/firefox
        path: ./firefox

    - name: Setup Pages
      uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

    - name: Setup Node.js environment
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
        package-manager-cache: false

    - name: Install packages and build
      working-directory: ./awdty
      run: |
        npm ci
        npm run build
        npm run test-ci

    - name: Check for Changes
      working-directory: ./awdty
      id: check_changes
      run: |
        if [[ -n "$(git diff --exit-code src/data/propagationHistory.json)" ]]; then
          echo "History Changes detected."
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "No history changes detected."
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Conditionally update history data
      working-directory: ./awdty
      if: steps.check_changes.outputs.has_changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_HOST: github.com
      # Using `persist-credentials: false` in the checkout means we'll need to use
      # gh to configure git to use the Github CLI as a credential helper. This will use the
      # GH_TOKEN in the env without that being persisted.
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add 'src/data/**/propagationHistory.json' 'src/data/propagationHistory.json'
        git commit -m "Update history data $(git -C ../mozilla-unified show -s --format=%cs)"
        gh auth setup-git
        git push https://github.com/FirefoxUX/arewedesigntokensyet.git main

    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        # Upload entire repository
        path: './awdty/build'

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
